apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cluster-a-vault-issuer
  namespace: cert-manager
spec:
  vault:
    server: http://172.18.0.7:8200
    path: cluster-a-pki/sign/nonprod
    auth:
      kubernetes:
        mountPath: /v1/auth/cluster-a
        role: cluster-a-issuer
        secretRef:
          name: cluster-a-issuer-sa-secret
          key: token
