apiVersion: v1
kind: Secret
metadata:
  name: cluster-a-issuer-token
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: cluster-a-issuer
type: kubernetes.io/service-account-token