---
apiVersion: v1
kind: Service
metadata:
  name: external-vault
spec:
  ports:
  - protocol: TCP
    port: 8200
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-vault
subsets:
  - addresses:
      - ip: '172.18.0.13'
    ports:
      - port: 8200
