apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: istio-ca-issuer
  namespace: istio-system
spec:
  vault:
    server: http://172.18.0.7:8200
    path: cluster-a-pki/sign/istio-ca
    auth:
      tokenSecretRef:
          name: cert-manager-vault-token
          key: token
