apiVersion: v1
kind: Pod
metadata: 
  name: app
  namespace: default
  labels:
    app: app
spec:
  containers:
  - name: frontend
    image: busybox
    volumeMounts:
    - mountPath: "/tls"
      name: tls
    command: [ "sleep", "1000000" ]
  volumes:
  - name: tls
    csi:
      driver: csi.cert-manager.io
      readOnly: true
      volumeAttributes:
        csi.cert-manager.io/issuer-name: vault-issuer
        csi.cert-manager.io/issuer-kind: ClusterIssuer
        csi.cert-manager.io/common-name: domain.net
        csi.cert-manager.io/dns-names: ${POD_NAME}.${POD_NAMESPACE}.apps.nonprod.cluster-a.domain.net