apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-secret
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: vault-auth-sa
type: kubernetes.io/service-account-token